// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

// Defines values for HealthResponseStatus.
const (
	Healthy   HealthResponseStatus = "healthy"
	Unhealthy HealthResponseStatus = "unhealthy"
)

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	// Status ヘルスステータス
	Status HealthResponseStatus `json:"status"`

	// Timestamp レスポンスの時刻
	Timestamp time.Time `json:"timestamp"`

	// Version API バージョン
	Version *string `json:"version,omitempty"`
}

// HealthResponseStatus ヘルスステータス
type HealthResponseStatus string

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ヘルスチェック
	// (GET /health)
	HealthCheck(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// HealthCheck converts echo context to params.
func (w *ServerInterfaceWrapper) HealthCheck(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.HealthCheck(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/health", wrapper.HealthCheck)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7xTwU4UQRD9lU3pcdgZFjWkbxsvbuKBqCfJHtregh2cmW67e0BC9jDTieFCNGqCHLzg",
	"AUWFGGJc1OjHtAt+humeAXZXvJrMoaZTVe/Vq1cbwHgqeIaZVkA2QLE+ptSHt5Amun8HleCZQvciJBco",
	"dYxVqqY691EPFZOx0DHPgIA1r6x5b8tj95kn1ny35U9bHkMAmOUpkEXo+9brEECencXdAPAxTUWCQMYS",
	"9LpwD0rLOFuGQQA6TlFpmorLkD94zNfWHLmgODjZKUeb32C8dStq3ZiJ5mZmr92bjUjkvvsQwBKXKdVA",
	"oEc1zjiQy8BXUSqPNQ3dXug0rHnmhx1as2fN0QTqbDNqRn93HAQg8VEeS+w5XWpJx4fsntfwByvINAxc",
	"UZwtcUeC8UxTpl2Y0RRrIndzIbjUjvAky7V2BwJIYob1Rs+KBGV9bLSaUaWw9pzX2p1Ge8FVnI9dzzEI",
	"gAvMqIiBwFw9mqC67+0QVttz4TLqS9ZU7lqzbc2+LT95wb5Ugtni4F/eseXz092vv/e3bLFtix+22AFP",
	"QVLXs9MDUtv1Zh/ZQ3CqVrb1hFpRdCYWZp4QFSKJmS8OV1S10Mr6LroqcQkIXAkvbiOsDyOcugq/jcnx",
	"Tj6+GQ2HttifsqNT7Xo09x+Z2PKzU9C8sOXxaPPd6cu3v4Zbo6eH3ncqT1Mq1ycO1hS23LPG2PLQmZAu",
	"q4trha5HUCidG4AsTq/1Nmc0afRwFRMuUjdeALlM3DVrLUgYJi6hz5Um89G8M9F0hwXJeznzP+OlioQh",
	"FXGzvqYm4ykMuoM/AQAA//8ykExquwQAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
