// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for CallPersonaRequestPresetKey.
const (
	Nenshu  CallPersonaRequestPresetKey = "nenshu"
	Yarigai CallPersonaRequestPresetKey = "yarigai"
)

// Defines values for HealthResponseStatus.
const (
	Healthy   HealthResponseStatus = "healthy"
	Unhealthy HealthResponseStatus = "unhealthy"
)

// Defines values for MessageSenderType.
const (
	MessageSenderTypePersona MessageSenderType = "persona"
	MessageSenderTypeUser    MessageSenderType = "user"
)

// Defines values for PersonaPersonaType.
const (
	Custom PersonaPersonaType = "custom"
	Preset PersonaPersonaType = "preset"
)

// CallPersonaRequest defines model for CallPersonaRequest.
type CallPersonaRequest struct {
	// PresetKey プリセット先輩のキー
	PresetKey CallPersonaRequestPresetKey `json:"preset_key"`
}

// CallPersonaRequestPresetKey プリセット先輩のキー
type CallPersonaRequestPresetKey string

// Chat defines model for Chat.
type Chat struct {
	CreatedAt time.Time          `json:"created_at"`
	Id        openapi_types.UUID `json:"id"`

	// LastMessage 最新メッセージのプレビュー
	LastMessage *string `json:"last_message,omitempty"`

	// Participants 参加中のプリセット先輩
	Participants *[]Persona `json:"participants,omitempty"`
	Persona      Persona    `json:"persona"`
	Title        *string    `json:"title,omitempty"`
	UpdatedAt    time.Time  `json:"updated_at"`
}

// CreateChatRequest defines model for CreateChatRequest.
type CreateChatRequest struct {
	Persona CreatePersonaInput `json:"persona"`

	// Title チャットタイトル
	Title *string `json:"title,omitempty"`
}

// CreatePersonaInput defines model for CreatePersonaInput.
type CreatePersonaInput struct {
	// Age 年齢
	Age int `json:"age"`

	// AnnualIncome 年収（万円）
	AnnualIncome int `json:"annual_income"`

	// Gender 性別
	Gender string `json:"gender"`

	// Name 先輩の名前
	Name string `json:"name"`

	// Occupation 職業
	Occupation string `json:"occupation"`

	// SystemPrompt システムプロンプト
	SystemPrompt *string `json:"system_prompt,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	// Status ヘルスステータス
	Status HealthResponseStatus `json:"status"`

	// Timestamp レスポンスの時刻
	Timestamp time.Time `json:"timestamp"`

	// Version API バージョン
	Version string `json:"version"`
}

// HealthResponseStatus ヘルスステータス
type HealthResponseStatus string

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	CreatedAt time.Time `json:"created_at"`

	// DisplayName 表示名
	DisplayName string `json:"display_name"`

	// Email メールアドレス
	Email string `json:"email"`

	// FirebaseUid Firebase UID
	FirebaseUid string `json:"firebase_uid"`

	// Id ユーザーID
	Id        openapi_types.UUID `json:"id"`
	UpdatedAt time.Time          `json:"updated_at"`
}

// Message defines model for Message.
type Message struct {
	ChatId openapi_types.UUID `json:"chat_id"`

	// Content メッセージ本文
	Content    string             `json:"content"`
	CreatedAt  time.Time          `json:"created_at"`
	Id         openapi_types.UUID `json:"id"`
	Persona    *Persona           `json:"persona,omitempty"`
	SenderType MessageSenderType  `json:"sender_type"`
}

// MessageSenderType defines model for Message.SenderType.
type MessageSenderType string

// MessageList defines model for MessageList.
type MessageList struct {
	// HasMore さらに古いメッセージが存在するか
	HasMore  bool      `json:"has_more"`
	Messages []Message `json:"messages"`
}

// Persona defines model for Persona.
type Persona struct {
	Age *int `json:"age,omitempty"`

	// AnnualIncome 年収（万円）
	AnnualIncome *int               `json:"annual_income,omitempty"`
	Gender       *string            `json:"gender,omitempty"`
	Id           openapi_types.UUID `json:"id"`
	Name         string             `json:"name"`
	Occupation   *string            `json:"occupation,omitempty"`
	PersonaType  PersonaPersonaType `json:"persona_type"`

	// PresetKeyId プリセットキー（preset の場合のみ）
	PresetKeyId *string `json:"preset_key_id,omitempty"`
}

// PersonaPersonaType defines model for Persona.PersonaType.
type PersonaPersonaType string

// SendMessageRequest defines model for SendMessageRequest.
type SendMessageRequest struct {
	// Content ユーザーのメッセージ本文
	Content string `json:"content"`
}

// SendMessageResponse defines model for SendMessageResponse.
type SendMessageResponse struct {
	// Replies AI先輩からの応答（複数の先輩が参加している場合は複数）
	Replies     []Message `json:"replies"`
	UserMessage Message   `json:"user_message"`
}

// ListMessagesParams defines parameters for ListMessages.
type ListMessagesParams struct {
	// Limit 取得件数（デフォルト 50）
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Before このIDより前のメッセージを取得（カーソルページネーション）
	Before *openapi_types.UUID `form:"before,omitempty" json:"before,omitempty"`
}

// CreateChatJSONRequestBody defines body for CreateChat for application/json ContentType.
type CreateChatJSONRequestBody = CreateChatRequest

// CallPersonaJSONRequestBody defines body for CallPersona for application/json ContentType.
type CallPersonaJSONRequestBody = CallPersonaRequest

// SendMessageJSONRequestBody defines body for SendMessage for application/json ContentType.
type SendMessageJSONRequestBody = SendMessageRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// チャット一覧
	// (GET /chats)
	ListChats(ctx echo.Context) error
	// チャット作成
	// (POST /chats)
	CreateChat(ctx echo.Context) error
	// プリセット先輩を呼ぶ
	// (POST /chats/{chatId}/call-persona)
	CallPersona(ctx echo.Context, chatId openapi_types.UUID) error
	// メッセージ一覧
	// (GET /chats/{chatId}/messages)
	ListMessages(ctx echo.Context, chatId openapi_types.UUID, params ListMessagesParams) error
	// メッセージ送信
	// (POST /chats/{chatId}/messages)
	SendMessage(ctx echo.Context, chatId openapi_types.UUID) error
	// ヘルスチェック
	// (GET /health)
	HealthCheck(ctx echo.Context) error
	// ログイン
	// (POST /login)
	Login(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// ListChats converts echo context to params.
func (w *ServerInterfaceWrapper) ListChats(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListChats(ctx)
	return err
}

// CreateChat converts echo context to params.
func (w *ServerInterfaceWrapper) CreateChat(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateChat(ctx)
	return err
}

// CallPersona converts echo context to params.
func (w *ServerInterfaceWrapper) CallPersona(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "chatId" -------------
	var chatId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "chatId", ctx.Param("chatId"), &chatId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter chatId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CallPersona(ctx, chatId)
	return err
}

// ListMessages converts echo context to params.
func (w *ServerInterfaceWrapper) ListMessages(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "chatId" -------------
	var chatId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "chatId", ctx.Param("chatId"), &chatId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter chatId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListMessagesParams
	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "before" -------------

	err = runtime.BindQueryParameter("form", true, false, "before", ctx.QueryParams(), &params.Before)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter before: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListMessages(ctx, chatId, params)
	return err
}

// SendMessage converts echo context to params.
func (w *ServerInterfaceWrapper) SendMessage(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "chatId" -------------
	var chatId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "chatId", ctx.Param("chatId"), &chatId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter chatId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SendMessage(ctx, chatId)
	return err
}

// HealthCheck converts echo context to params.
func (w *ServerInterfaceWrapper) HealthCheck(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.HealthCheck(ctx)
	return err
}

// Login converts echo context to params.
func (w *ServerInterfaceWrapper) Login(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Login(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/chats", wrapper.ListChats)
	router.POST(baseURL+"/chats", wrapper.CreateChat)
	router.POST(baseURL+"/chats/:chatId/call-persona", wrapper.CallPersona)
	router.GET(baseURL+"/chats/:chatId/messages", wrapper.ListMessages)
	router.POST(baseURL+"/chats/:chatId/messages", wrapper.SendMessage)
	router.GET(baseURL+"/health", wrapper.HealthCheck)
	router.POST(baseURL+"/login", wrapper.Login)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xaW28TSRb+K1HtPhpsbivkNwZ2tJYYCQ3sy6LIKtqVuIe+0Rd2LWTJ1Q1JQxKSCYTA",
	"bHYJkBsJSWAzSxxiyH/Zcjvmib+wqmq3u9tdjp0ZyO5oRkKibVefOud85/KdqtwCgiprqoIU0wDZW8AQ",
	"ikiG7PE8lKRLSDdUBX6LbljIMOm3mq5qSDdFZPifkIHM/HVUop8KyBB0UTNFVQFZQJxZ4qwSe5c4DnFc",
	"747brL0keIPY68SpgRRAiiWD7FVQgro4DEWQAgpSjKIFBlPALGkIZIFh6qIyDMrlFNDRDUvUUYG+Edk2",
	"XKte+w4JJiinwPki5Ogq6AiaqJD3fxtSdZk+gQI00TFTlBFI7JoCYiG21rLEAm+ZBA0zLyPDgMMo6YjG",
	"XKXx6DVxnlFHUHfUiF2ljqAOekWcB8RZ9D2SEKxB3RQFUYMteOKCvUnbuzdfr64Hwjq9DVJANJHMXv29",
	"joZAFvwuHQKebqGdbsFMd2ypAHUdlpgGrZ8OIUE0JeaFhDWWVjgkAh24M+8HGqWiiMaEc2OCraWR0T2Y",
	"+zPVl9QyOKdolhmzujMJMHFe+JgQe4/YC/TBWaPh/zcoa/QdwDLiBYPv+f7fq8210Z6eCHTtbmpMwYSt",
	"3ED1dn78+P55VLVTZ9ryRcVEw0inG0BFsaCUFxVBlflivMn7n2puvTrqjYx8qt2NijybyfBkDiOlgHRO",
	"8lSWPXcx5q79h9uNyjIvXRTI1SeoPN7UhHd3IibLc0ca/5wizm7DXdqfWWynTUK0KgiWBn2JnRs08XZj",
	"cT0mN3eF2FvE2SL2v4mzRpF3tojj8iQbJcNEcl7TVVkzORFkbxN7hzgjxJlnSb7ORM1ypXVECfNH27cp",
	"hnrMlE4seeH0R11X9W+RoamKgThlVS1Esz0CaaQgHqwmExGu5ynxJwQls9hdC8OEpmXw8u8x8/9O4MMa",
	"y8KdSPspMtElWkKU4HkwimW4IIEdrVqGCWWNt/Mrtuc/WBTsELzReGJ77m4sTE5mTv7hWObUsROnr5zI",
	"ZDP0319Aqs/mdBPpBjcez13KDRBnqtVonGXibMV2PXE8czzTM3haLo0aGe7Jw+iiOiwqBwTKT+i/BdHQ",
	"JFjK8xO7+Wxlf+GdNzXBexXJUJR4sDyjfqEx8Zw4d32UeO8PiTq6Bg2Ut3wSEBfzdevXgT/nLnQnDp1b",
	"LzFI3hKnxt7qySs+T8OMWRI4psO3h2um34SZ3YFxEZr5PkmToComUswuEIVMqTH3qvFolCvhyzG6w9Me",
	"gxXZvC/pVru6WAarvMl+fRBigRvjUkOXxUw/AKCLIo/nFKGRl1Wdx1bwDLHvErzmTS4QfDtBWce99cfe",
	"3ArBT4g9RvBY6LlrqiohqETKPtuqL/YZRFOCfXa4pi04FZrAM/5SiB2X9HweQnMQhfmpUReUuR7so1u0",
	"JoJPsAxTlWn4sYGJE32pyCyV5xet2FzhD2+faq7/2gBlVfM/elMuHUHwXsw1fZD4ILCZ4TwsLyOl0IqP",
	"rrz9gEISFlw2IvHrStgY67v3CN6o787U343RLHj9PcGzzb1tmgt4nGCb4BcEL/2nstTYvN+YXfT2nhA8",
	"y37dIHiZ5gUeJxXcHF313BHa8t2pjzPbBI83bj8l+DFNLnuc4FWCJwleIhW7p7cC43o6p1vb1ZEmtR47",
	"WEIuIMZjLOk3vL25/fWHn2puc2G0MfOaftNaMO5PmszWJWquPRagvukv9oH/eemeYsUyOkf3JabDYTEZ",
	"qbb5Sf+xmi1YumiWLlOZvo++QlBH+jnLLNJP19inr4O8bXf93IWBK+p1RAk004eVQLY2BLRomhoo021E",
	"ZUgNAhUKLFD9TGdM7bKlaarOAI0D9NdzOZACkiigFrDBSxoUimjg5PFMZPCkqwfOXcpFOFpA9Gj90JAC",
	"NRFkwakW99OgWWQGp2mzYU/DiJtD68R+zebWrUQ+hbNtvVppLi0Te9qbfOR9mGWR8oHgJ4DtrbPSlSuA",
	"LKAt6TzbkWLjBy3b/WQm05HMUNMkUWCvpr8z/NLno993a2EnQcm+knB10hT61unMiUOpdJAm8SmKo0Jz",
	"daK5UiP2CnFeEqfmx6cly1Av8RVMARMOG6xGMH8O0mKuGtwR0p+A9ogz3x6GG84db/4NwSv1amV/e5rg",
	"tfhZxXT9/VzDneqOZHiiAvwMRIb5lVoofTaXJY9syvFkN3ULlRNh9Pkw86OnR7QwLzXcKe/eUz9mMkcX",
	"M6wzb9KYoZOmW69ONNZf/D9HLnMWJ3LLqVYdSt+i/+UK5bQAJelYhIZ3CW3uIbM9HYtlvOZ9XyN4yxt9",
	"R8O5gj/i+979Xdrqaz80X74h9nRzdZ3YDwier1fvEbzsuYvNpUf7bGwPBsUpWgRpGk039x4ekBbhsTkr",
	"szqUkYl0au4tIFKdaekNOE8W+PaCzrhORdDpwRvLg18o/5IXAEecgGGP54Q+/3bBJzG/ZaKfiXT/00fp",
	"hWjWfSD4KcGbXZAaby6NEbwQsM9Vgm8nKgc/t1kyv41UkfZgyC0k0Xm0C8UJtfZG7iQnhUORm2/CKfVI",
	"kj+VvBWiStZ33zJa7hJnlDgzxH5JnDXiuANnMi2uTtfesJBeCtWRRFk0QXT3AhqClmSC7BnOqX1yb4If",
	"ELyRu0Bsl9j3vLsTSWe23Uh1s9fYl++Zbj8EB5YT7GHbP7nsru01NKTqCBy6Uv4M0tlHsWJnLtzc4MTU",
	"r7xC9FMDeF7jpn5X9nvgKQCxpz9WcH3vmc8MugzFvZp+ZBL/hTd9zoHLETd93qlG73zyQfR5+Keaey7X",
	"Bs6bWiN2hZaR30jBLzDlfWC7d3v/dq57c6fs3ecRb6JthVUC/t0gsaf3n79rrk50z3f/OvJ8EQnXwRds",
	"KR23nhznNtZfeNUq9WP8upGifCZz6gg1YTfdNeI8IPaO577cf7hSr054k5uxgzaQvToYxzqAwMHEXma4",
	"b0awboHrIy2pw6LSfRRMHM4NEHu6sTBHg5/V9lgjsKf3n+x+HP9Xm6b25HZs9y8Idvz6lJtI4VFc9MDh",
	"fz3qh9jGj0+vDpY7wA71j2AMLR/hPkQh/WbQVON6XVQFKA0U0E0kqZrsX5FZutQ6hc2m0xJdUFQNM3s2",
	"czYDksz1kq4WLKH1RxHhq0Y2nYaaeLx1R3BcUGVQHiz/NwAA//8jkOq5NycAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
