// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for HealthResponseStatus.
const (
	Healthy   HealthResponseStatus = "healthy"
	Unhealthy HealthResponseStatus = "unhealthy"
)

// Defines values for MessageSenderType.
const (
	MessageSenderTypePersona MessageSenderType = "persona"
	MessageSenderTypeUser    MessageSenderType = "user"
)

// Defines values for PersonaPersonaType.
const (
	Custom PersonaPersonaType = "custom"
	Preset PersonaPersonaType = "preset"
)

// Chat defines model for Chat.
type Chat struct {
	CreatedAt time.Time          `json:"created_at"`
	Id        openapi_types.UUID `json:"id"`

	// LastMessage 最新メッセージのプレビュー
	LastMessage *string `json:"last_message,omitempty"`

	// Participants 参加中のプリセット先輩
	Participants *[]Persona `json:"participants,omitempty"`
	Persona      Persona    `json:"persona"`
	Title        *string    `json:"title,omitempty"`
	UpdatedAt    time.Time  `json:"updated_at"`
}

// CreateChatRequest defines model for CreateChatRequest.
type CreateChatRequest struct {
	Persona CreatePersonaInput `json:"persona"`

	// Title チャットタイトル
	Title *string `json:"title,omitempty"`
}

// CreatePersonaInput defines model for CreatePersonaInput.
type CreatePersonaInput struct {
	// Age 年齢
	Age int `json:"age"`

	// AnnualIncome 年収（万円）
	AnnualIncome int `json:"annual_income"`

	// Gender 性別
	Gender string `json:"gender"`

	// Name 先輩の名前
	Name string `json:"name"`

	// Occupation 職業
	Occupation string `json:"occupation"`

	// SystemPrompt システムプロンプト
	SystemPrompt *string `json:"system_prompt,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	// Status ヘルスステータス
	Status HealthResponseStatus `json:"status"`

	// Timestamp レスポンスの時刻
	Timestamp time.Time `json:"timestamp"`

	// Version API バージョン
	Version string `json:"version"`
}

// HealthResponseStatus ヘルスステータス
type HealthResponseStatus string

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	CreatedAt time.Time `json:"created_at"`

	// DisplayName 表示名
	DisplayName *string `json:"display_name,omitempty"`

	// Email メールアドレス
	Email *string `json:"email,omitempty"`

	// FirebaseUid Firebase UID
	FirebaseUid string `json:"firebase_uid"`

	// Id ユーザーID
	Id        openapi_types.UUID `json:"id"`
	UpdatedAt time.Time          `json:"updated_at"`
}

// Message defines model for Message.
type Message struct {
	ChatId openapi_types.UUID `json:"chat_id"`

	// Content メッセージ本文
	Content    string             `json:"content"`
	CreatedAt  time.Time          `json:"created_at"`
	Id         openapi_types.UUID `json:"id"`
	Persona    *Persona           `json:"persona,omitempty"`
	SenderType MessageSenderType  `json:"sender_type"`
}

// MessageSenderType defines model for Message.SenderType.
type MessageSenderType string

// MessageList defines model for MessageList.
type MessageList struct {
	// HasMore さらに古いメッセージが存在するか
	HasMore  bool      `json:"has_more"`
	Messages []Message `json:"messages"`
}

// Persona defines model for Persona.
type Persona struct {
	Age *int `json:"age,omitempty"`

	// AnnualIncome 年収（万円）
	AnnualIncome *int               `json:"annual_income,omitempty"`
	Gender       *string            `json:"gender,omitempty"`
	Id           openapi_types.UUID `json:"id"`
	Name         string             `json:"name"`
	Occupation   *string            `json:"occupation,omitempty"`
	PersonaType  PersonaPersonaType `json:"persona_type"`

	// PresetKeyId プリセットキー（preset の場合のみ）
	PresetKeyId *string `json:"preset_key_id,omitempty"`
}

// PersonaPersonaType defines model for Persona.PersonaType.
type PersonaPersonaType string

// SendMessageRequest defines model for SendMessageRequest.
type SendMessageRequest struct {
	// Content ユーザーのメッセージ本文
	Content string `json:"content"`
}

// SendMessageResponse defines model for SendMessageResponse.
type SendMessageResponse struct {
	// Replies AI先輩からの応答（複数の先輩が参加している場合は複数）
	Replies     []Message `json:"replies"`
	UserMessage Message   `json:"user_message"`
}

// ListMessagesParams defines parameters for ListMessages.
type ListMessagesParams struct {
	// Limit 取得件数（デフォルト 50）
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Before このIDより前のメッセージを取得（カーソルページネーション）
	Before *openapi_types.UUID `form:"before,omitempty" json:"before,omitempty"`
}

// CreateChatJSONRequestBody defines body for CreateChat for application/json ContentType.
type CreateChatJSONRequestBody = CreateChatRequest

// SendMessageJSONRequestBody defines body for SendMessage for application/json ContentType.
type SendMessageJSONRequestBody = SendMessageRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// チャット一覧
	// (GET /chats)
	ListChats(ctx echo.Context) error
	// チャット作成
	// (POST /chats)
	CreateChat(ctx echo.Context) error
	// メッセージ一覧
	// (GET /chats/{chatId}/messages)
	ListMessages(ctx echo.Context, chatId openapi_types.UUID, params ListMessagesParams) error
	// メッセージ送信
	// (POST /chats/{chatId}/messages)
	SendMessage(ctx echo.Context, chatId openapi_types.UUID) error
	// ヘルスチェック
	// (GET /health)
	HealthCheck(ctx echo.Context) error
	// ログイン
	// (POST /login)
	Login(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// ListChats converts echo context to params.
func (w *ServerInterfaceWrapper) ListChats(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListChats(ctx)
	return err
}

// CreateChat converts echo context to params.
func (w *ServerInterfaceWrapper) CreateChat(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateChat(ctx)
	return err
}

// ListMessages converts echo context to params.
func (w *ServerInterfaceWrapper) ListMessages(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "chatId" -------------
	var chatId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "chatId", ctx.Param("chatId"), &chatId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter chatId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListMessagesParams
	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "before" -------------

	err = runtime.BindQueryParameter("form", true, false, "before", ctx.QueryParams(), &params.Before)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter before: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListMessages(ctx, chatId, params)
	return err
}

// SendMessage converts echo context to params.
func (w *ServerInterfaceWrapper) SendMessage(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "chatId" -------------
	var chatId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "chatId", ctx.Param("chatId"), &chatId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter chatId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SendMessage(ctx, chatId)
	return err
}

// HealthCheck converts echo context to params.
func (w *ServerInterfaceWrapper) HealthCheck(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.HealthCheck(ctx)
	return err
}

// Login converts echo context to params.
func (w *ServerInterfaceWrapper) Login(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Login(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/chats", wrapper.ListChats)
	router.POST(baseURL+"/chats", wrapper.CreateChat)
	router.GET(baseURL+"/chats/:chatId/messages", wrapper.ListMessages)
	router.POST(baseURL+"/chats/:chatId/messages", wrapper.SendMessage)
	router.GET(baseURL+"/health", wrapper.HealthCheck)
	router.POST(baseURL+"/login", wrapper.Login)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xZ608b2RX/V9BtPzrYeVWRv7FJV7WUldAm/dIIWcP4gmfjeWQeaS1kyTOTwBBgoSSE",
	"0NKGEF6BANmyXUxwlv+lx2OcT/wL1b3j8cx4rjHsJmwrrRQpg+fec885v/P4nTsjiJdFRZawpGsoPYI0",
	"Po9Fjj7ezHM6+V9RZQWruoDpr7yKOR3nst67IVkVyRPKcTq+pAsiRgmkFxWM0kjTVUEaRqUEEnKRtYYh",
	"5FjLCpymZ0WsadwwJhtyWONVQdEFWUJpVF8s15+/A/sV2DZYh2BXwaqAuQP2PNhvwX4K9irYVZZghVN1",
	"gRcUrmlkVLA7bblPlmqVbV/YJhVvg+24j51G9Q1KIEHHIt36WxUPoTT6TTJwW7Lps2Q/VjVZ4siJTRU4",
	"VeWKVIPmq3NIEPQC9ULMGkPJnROBUgKp+IEhqDiH0vcQ9b6vUSKMaET4QEuOPPgN5nVy9k26lkTG1/iB",
	"gTVGgJzRVE9S0+CMpBh6xOooRGCbYL/2MAHrCKwV8mBvoQTCf+FEhexBYG3TRZtgLR//vdLYGuvqCV/X",
	"zqZGFIzZygxU9+D7jx+Ww6pdvd6SL0g6HsYqOYCTJIMrZAWJl0W2GHf625OqU6uMuaOjJ9XxsMgbqRRL",
	"5jCWclhlJE953XVWI+46frZfL6+z0kXimPrQXABzx52ZcsenIrJcZ7T+zxmwD+vO2vHcaittYqJlnjcU",
	"zpPYfkDD3K+vbkfkZu6CtQf2Hlj/BnuLIG/vge2wJGtFTcdiVlFlUdEZEWTtg3UA9ijYSzTJt6moeaa0",
	"tiih/mj5NkFRj5jSjiUrnH6vqrL6NdYUWdIwo6zKuXC2hyANFcTT1aQigvUsJf6AuYKe76yFpnO6obHy",
	"7wX1/4HvwyrNwgMClmSI5PQ8FV0kJUTynwfCWAYLYtiRqqXpnKiwTn5Lz/wHjYIDMHfqC5brHEbC5Erq",
	"yu8upa5eunzt7uVUOkX+/QklzticHmJVY8ZjX3+mB+yZZqOx18Hei5x6uTfVm+oaPE2Xho0MzmRhdFse",
	"FqRTAuUn9N+coCkFrphlJ3bj1cbxynt3Zoq1FYucUGDB8or4hcTEMtjjHkqs/UOCigc5DWcNjwRExXzZ",
	"fNvzx8ytzsSh/eg1CskPYFfprq684tM0zIgl5+uaXwUp3AZmntOzZ2RHvCzpWNI7YBFQovri2/rzMaaE",
	"z0fdzs9vNFpNs56kkVYZMTRaYuON+TRofDdGpQYui5h+CkC3BRahyXNaVpRVFi0x58AaB3PLnV4B81GM",
	"m0662y/cxQ0wF8CaAHMi8NygLBcwJ4XqOz3qTDTTj6YYzWxzTUtwIjCBZXx/gB2T3Xwa5nIaV/mpUefX",
	"sy40o1O0xoKPNzRdFkn4qVjDOiP6/FfZ+7iYZVenyABBOWn1pOp423oIfVr63p1xyKxhHkVccwa27gc2",
	"NZyF5R0s5Zrx0ZGgn1JIgspKZyF2XQk6YO3wCZg7tcO52vsJkgXv/grmfONon+SCOQmmBeZrMNf+U16r",
	"735bn191jxbAnKdvd8BcJ3lhTkLZbIxtus4o6e3OzMe5fTAn649egvmCJJc1CeYmmNNgrkHZ6uot37iu",
	"zunUX1WsFJqPbXQg4zPgCZr0O+7R4vH2s5Oq01gZq8+9I780F0x6IyW1dY2Ya034qO96iz3gf166J2ix",
	"DA/MZxLT5rCIjETL/Lj/aM3mDVXQi3eITM9HX2BOxWqfoefJX4P0ry/9vG2198ytnrvyfUyYMtWHlkC6",
	"NgA0r+sKKpFjBGlI9gOV42mgeplOKdkdQ1FklQIaBejPfRmUQAWBx01g/U0Kx+dxz5XeVGjCJKt7+voz",
	"ITLmMzpSPxQscYqA0uhqk+QpnJ6nBidJs6FPw5iZQ9tgvaMD6l4sn4IhtlYpN9bWwZp1p5+7P87TSPkR",
	"zAVEz1Zp6crkUBqRlnSTnkiw8YKWnn4llWpLZk5RCgJPtya/0bzS56F/5tZCr3zifSXm6rgpZNe11OVz",
	"qXSaJtFxiaFCY3OqsVEFawPsN2BXvfg0RJFTi2wFE0jnhjVaI6g/B0gxlzXmrOiNOkdgL7Wm3rr92F36",
	"DsyNWqV8vD8L5lb0UmK29mGx7sx0RjK4OkFeBmJN/0LOFT+Zy+J3M6VosuuqgUuxMPp0mHnR0yVaqJfq",
	"zoz75KUXM6mLixnamXdJzJCR0qlVpurbr/+XI5c6ixG5pUSzDiVHyH+ZXCkZppEdKlMg2B19HG/w56pJ",
	"XwXkUuFUTsQ6VomKI0ggh5Fy6fOUNPJ0RO2xmAh5tAvXKyXit7ZEydrhD7SbOmCPgT0H1hsyk9pOz/VU",
	"s8WStQ8MrBYDdQqCKOgofHoOD3FGQUfp64xbtfjZYD4FcydzCywHrCfu+FTcmS03Et2sLfrjB6rb3/wL",
	"hSn6sO/dLHTWdhAPEeZ+HmcN/MxecQYeQUclZooxYuqXTzFy/rWLLDSh1mBONtYmwFzxieMmmI9iSc/y",
	"WpD3reQ+pWmdSt7Bmv1YNmtHr0hWl80OXBas2cbRs86JHyLQF5X3A5+nVzLmpAtulqxhpHs+eSB67fOk",
	"6vRlWsC5M1tglUkZ+bWr/h+mvAcsO+VJt/duzzs3d2vZv3n4LtxWaCVg392DNXu8/L6xOdU5373PBTfz",
	"mL+PPmNLafsqwXBuffu1W6kQP0Y/BxCUr6euXqAm9EtUFeynYB24zpvjZxu1ypQ7vRuZj1H63kAUax8C",
	"2wRrneK+G8K6Ca6HdEEeFqjK7Dofm6l7wJqtryyS4Ke1PdIIrNnjhcOPk/+iAL8Ec7crt6Onf0awo583",
	"mIkUTNDhOeGXZugBttFbj3sDpTawA/1DGHOGh/AZRGH1od9Uo3rdlnmu0JPDD3FBVkTvZttQC83Lk3Qy",
	"WSAL8rKmp2+kbqRQnLn2q3LO4JsfLYOtWjqZ5BSht3m118vLIioNlP4bAAD//+o+evMdIgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
