// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd_fpqz74qizvoa2k32keXarFj58ccSGg',
    appId: '1:887016287518:web:aa75a4414b14d1ed736d0f',
    messagingSenderId: '887016287518',
    projectId: 'ss-wai-eb7ec',
    authDomain: 'ss-wai-eb7ec.firebaseapp.com',
    storageBucket: 'ss-wai-eb7ec.firebasestorage.app',
    measurementId: 'G-DMY30EQHZ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrlpLbryUkv7YtpuhVHVvC-X4426tBWJs',
    appId: '1:887016287518:android:c7824495202e0b20736d0f',
    messagingSenderId: '887016287518',
    projectId: 'ss-wai-eb7ec',
    storageBucket: 'ss-wai-eb7ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9QLALOjD2aMH94eVKroHianRIGCYawr8',
    appId: '1:887016287518:ios:c4f5da27cabb6c14736d0f',
    messagingSenderId: '887016287518',
    projectId: 'ss-wai-eb7ec',
    storageBucket: 'ss-wai-eb7ec.firebasestorage.app',
    iosBundleId: 'com.example.wai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9QLALOjD2aMH94eVKroHianRIGCYawr8',
    appId: '1:887016287518:ios:c4f5da27cabb6c14736d0f',
    messagingSenderId: '887016287518',
    projectId: 'ss-wai-eb7ec',
    storageBucket: 'ss-wai-eb7ec.firebasestorage.app',
    iosBundleId: 'com.example.wai',
  );
}
