// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package registry

import (
	"context"
	"github.com/S-s-dev-team/wAI/internal/domain/config"
	"github.com/S-s-dev-team/wAI/internal/handler"
	"github.com/S-s-dev-team/wAI/internal/repository"
	"github.com/S-s-dev-team/wAI/internal/usecase"
	"github.com/google/generative-ai-go/genai"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeApp(ctx context.Context) (*App, error) {
	vars, err := config.New(ctx)
	if err != nil {
		return nil, err
	}
	client, err := FirebaseAuthProvider(ctx, vars)
	if err != nil {
		return nil, err
	}
	authRepository := repository.NewAuth(client)
	db, err := DatabaseProvider(vars)
	if err != nil {
		return nil, err
	}
	userRepository := repository.NewUser(db)
	personaRepository := repository.NewPersona(db)
	login := usecase.NewLogin(authRepository, userRepository)
	chatRepository := repository.NewChat(db)
	chatUsecase := usecase.NewChatUsecase(chatRepository, personaRepository)
	messageRepository := repository.NewMessage(db)
	chatParticipantRepository := repository.NewChatParticipant(db)
	genaiClient, err := GeminiAPIProvider(ctx, vars)
	if err != nil {
		return nil, err
	}
	aiRepository := repository.NewGemini(genaiClient)
	messageUsecase := usecase.NewMessageUsecase(messageRepository, personaRepository, chatParticipantRepository, aiRepository)
	server := handler.NewServer(authRepository, userRepository, personaRepository, login, chatUsecase, messageUsecase)
	app := &App{
		Config: vars,
		Server: server,
		DB:     db,
		GenAI:  genaiClient,
	}
	return app, nil
}

// wire.go:

type App struct {
	Config *config.Vars
	Server *handler.Server
	DB     *gorm.DB
	GenAI  *genai.Client
}
