// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package registry

import (
	"context"
	"github.com/S-s-dev-team/wAI/internal/domain/config"
	"github.com/S-s-dev-team/wAI/internal/handler"
	"github.com/S-s-dev-team/wAI/internal/repository"
	"github.com/S-s-dev-team/wAI/internal/usecase"
	"github.com/google/generative-ai-go/genai"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeApp(ctx context.Context) (*App, error) {
	vars, err := config.New(ctx)
	if err != nil {
		return nil, err
	}
	client, err := FirebaseAuthProvider(ctx, vars)
	if err != nil {
		return nil, err
	}
	authRepository := repository.NewAuth(client)
	db, err := DatabaseProvider(vars)
	if err != nil {
		return nil, err
	}
	userRepository := repository.NewUser(db)
	login := usecase.NewLogin(authRepository, userRepository)
	handlerLogin := handler.NewLogin(login)
	health := usecase.NewHealth()
	handlerHealth := handler.NewHealth(health)
	genaiClient, err := GeminiAPIProvider(ctx, vars)
	if err != nil {
		return nil, err
	}
	app := &App{
		LoginHandler:  handlerLogin,
		HealthHandler: handlerHealth,
		DB:            db,
		GenAI:         genaiClient,
	}
	return app, nil
}

// wire.go:

type App struct {
	LoginHandler  *handler.Login
	HealthHandler *handler.Health
	DB            *gorm.DB
	GenAI         *genai.Client
}
