/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * ログイン
         * @description Firebase ID Token を検証し、ユーザーを登録または取得します
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * チャット一覧
         * @description ログインユーザーのチャット一覧を取得します
         */
        get: operations["listChats"];
        put?: never;
        /**
         * チャット作成
         * @description カスタム先輩の情報と一緒にチャットを作成します
         */
        post: operations["createChat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chats/{chatId}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * メッセージ一覧
         * @description チャット内のメッセージ一覧を取得します
         */
        get: operations["listMessages"];
        put?: never;
        /**
         * メッセージ送信
         * @description ユーザーのメッセージを送信し、AI先輩からの応答を返します
         */
        post: operations["sendMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * ヘルスチェック
         * @description アプリケーションのヘルスステータスを確認します
         */
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginResponse: {
            /**
             * Format: uuid
             * @description ユーザーID
             */
            id: string;
            /** @description Firebase UID */
            firebase_uid: string;
            /** @description メールアドレス */
            email?: string;
            /** @description 表示名 */
            display_name?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ErrorResponse: {
            code: number;
            message: string;
        };
        CreateChatRequest: {
            /**
             * @description チャットタイトル
             * @example キャリア相談
             */
            title?: string;
            persona: components["schemas"]["CreatePersonaInput"];
        };
        CreatePersonaInput: {
            /**
             * @description 先輩の名前
             * @example 分析・戦略先輩
             */
            name: string;
            /**
             * @description 性別
             * @example 男性
             */
            gender: string;
            /**
             * @description 年齢
             * @example 35
             */
            age: number;
            /**
             * @description 職業
             * @example ITコンサルタント
             */
            occupation: string;
            /**
             * @description 年収（万円）
             * @example 800
             */
            annual_income: number;
            /** @description システムプロンプト */
            system_prompt?: string;
        };
        Chat: {
            /** Format: uuid */
            id: string;
            title?: string;
            persona: components["schemas"]["Persona"];
            /** @description 参加中のプリセット先輩 */
            participants?: components["schemas"]["Persona"][];
            /** @description 最新メッセージのプレビュー */
            last_message?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        Persona: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            persona_type: "custom" | "preset";
            /** @description プリセットキー（preset の場合のみ） */
            preset_key_id?: string;
            name: string;
            gender?: string;
            age?: number;
            occupation?: string;
            /** @description 年収（万円） */
            annual_income?: number;
        };
        SendMessageRequest: {
            /**
             * @description ユーザーのメッセージ本文
             * @example 今の仕事に少し迷いがあって…毎日忙しいのですが、自分の成長が感じられなくて。
             */
            content: string;
        };
        SendMessageResponse: {
            user_message: components["schemas"]["Message"];
            /** @description AI先輩からの応答（複数の先輩が参加している場合は複数） */
            replies: components["schemas"]["Message"][];
        };
        MessageList: {
            messages: components["schemas"]["Message"][];
            /** @description さらに古いメッセージが存在するか */
            has_more: boolean;
        };
        Message: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            chat_id: string;
            /** @enum {string} */
            sender_type: "user" | "persona";
            /** @description 送信者がpersonaの場合の先輩情報 */
            persona?: components["schemas"]["Persona"];
            /** @description メッセージ本文 */
            content: string;
            /** Format: date-time */
            created_at: string;
        };
        HealthResponse: {
            /**
             * @description ヘルスステータス
             * @example healthy
             * @enum {string}
             */
            status: "healthy" | "unhealthy";
            /**
             * Format: date-time
             * @description レスポンスの時刻
             * @example 2026-03-14T10:00:00Z
             */
            timestamp: string;
            /**
             * @description API バージョン
             * @example 1.0.0
             */
            version: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ログイン成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description 認証エラー */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listChats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description チャット一覧 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Chat"][];
                };
            };
            /** @description 認証エラー */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createChat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateChatRequest"];
            };
        };
        responses: {
            /** @description チャット作成成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Chat"];
                };
            };
            /** @description リクエスト不正 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 認証エラー */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listMessages: {
        parameters: {
            query?: {
                /** @description 取得件数（デフォルト 50） */
                limit?: number;
                /** @description このIDより前のメッセージを取得（カーソルページネーション） */
                before?: string;
            };
            header?: never;
            path: {
                chatId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description メッセージ一覧 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageList"];
                };
            };
            /** @description 認証エラー */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description チャットが見つからない */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    sendMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chatId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendMessageRequest"];
            };
        };
        responses: {
            /** @description メッセージ送信成功（AI応答を含む） */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SendMessageResponse"];
                };
            };
            /** @description リクエスト不正 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 認証エラー */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description チャットが見つからない */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 正常なレスポンス */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description サービス利用不可 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
